<?php

    return [
        'basic' => [
            'max_apiaries' => 1,
            'max_beehives' => 5,
            'max_inspections' => PHP_INT_MAX,
            'max_custom_checklists' => 1,
            'data_storage' => PHP_INT_MAX,
            'access_features' => [
                'access_to_all_checklist_categories' => true,
                'download_data' => true,
                'language_selection' => true,
                'collaboration_group' => false,
                'offline_data_entry' => false,
                'connect_beep_base' => true,
                'connect_another_system' => false,
                'access_sensor_data' => true,
                'compare_hives' => false,
                'net_weight_calculation' => false,
                'setting_alert_rules' => true,
                'access_data_analysis_models' => false,
                'public_dashboard' => false,
                'add_research_project' => false,
                'add_research_checklists' => false,
                'add_protocols' => false,
                'invite_participants' => false,
                'monitor_data_collection' => false,
                'sample_collection_and_result_sharing' => false,
                'adding_algorithm_or_prediction_model' => false,
                'download_data_research_participants' => false,
                'read_or_write_data_with_beep_api' => true,
            ],
        ],
        'pro' => [
            'max_apiaries' => 5,
            'max_beehives' => 50,
            'max_inspections' => PHP_INT_MAX,
            'max_custom_checklists' => 3,
            'data_storage' => PHP_INT_MAX,
            'access_features' => [
                'access_to_all_checklist_categories' => true,
                'download_data' => true,
                'language_selection' => true,
                'collaboration_group' => true,
                'offline_data_entry' => true,
                'connect_beep_base' => true,
                'connect_another_system' => true,
                'access_sensor_data' => true,
                'compare_hives' => true,
                'net_weight_calculation' => true,
                'setting_alert_rules' => true,
                'access_data_analysis_models' => true,
                'public_dashboard' => false,
                'add_research_project' => false,
                'add_research_checklists' => false,
                'add_protocols' => false,
                'invite_participants' => false,
                'monitor_data_collection' => false,
                'sample_collection_and_result_sharing' => false,
                'adding_algorithm_or_prediction_model' => false,
                'download_data_research_participants' => false,
                'read_or_write_data_with_beep_api' => true,
            ],
        ],
        'advanced' => [
            'max_apiaries' => PHP_INT_MAX,
            'max_beehives' => PHP_INT_MAX,
            'max_inspections' => PHP_INT_MAX,
            'max_custom_checklists' => PHP_INT_MAX,
            'data_storage' => PHP_INT_MAX,
            'access_features' => [
                'access_to_all_checklist_categories' => true,
                'download_data' => true,
                'language_selection' => true,
                'collaboration_group' => true,
                'offline_data_entry' => true,
                'connect_beep_base' => true,
                'connect_another_system' => true,
                'access_sensor_data' => true,
                'compare_hives' => true,
                'net_weight_calculation' => true,
                'setting_alert_rules' => true,
                'access_data_analysis_models' => true,
                'public_dashboard' => true,
                'add_research_project' => false,
                'add_research_checklists' => false,
                'add_protocols' => false,
                'invite_participants' => false,
                'monitor_data_collection' => false,
                'sample_collection_and_result_sharing' => false,
                'adding_algorithm_or_prediction_model' => true,
                'download_data_research_participants' => false,
                'read_or_write_data_with_beep_api' => true,
            ],
        ],
        'research' => [
            'max_apiaries' => 1,
            'max_beehives' => 5,
            'max_inspections' => PHP_INT_MAX,
            'max_custom_checklists' => 1,
            'data_storage' => PHP_INT_MAX,
            'access_features' => [
                'access_to_all_checklist_categories' => true,
                'download_data' => true,
                'language_selection' => true,
                'collaboration_group' => true,
                'offline_data_entry' => true,
                'connect_beep_base' => true,
                'connect_another_system' => true,
                'access_sensor_data' => true,
                'compare_hives' => true,
                'net_weight_calculation' => true,
                'setting_alert_rules' => true,
                'access_data_analysis_models' => true,
                'public_dashboard' => true,
                'add_research_project' => true,
                'add_research_checklists' => true,
                'add_protocols' => true,
                'invite_participants' => true,
                'monitor_data_collection' => true,
                'sample_collection_and_result_sharing' => true,
                'adding_algorithm_or_prediction_model' => true,
                'download_data_research_participants' => true,
                'read_or_write_data_with_beep_api' => true,
            ],
        ],
    ];

?>